---
apiVersion: v1
kind: Namespace
metadata:
  name: gaia
  labels:
    name: gaia
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gaia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
    repoURL: https://github.com/gaia-app/chart.git
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gaia
  syncPolicy:
    automated:
      selfHeal: true
