apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas-functions
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: openfaas-fn
  project: default
  source:
    # TODO: move this to another repo
    path: openfaas-functions
    repoURL: https://github.com/pypeaday/argocd-helm.git
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
