apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  labels:
    name: openfaas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
        - name: openfaasPro
          value: "true"
        - name: operator
          value: "true"
        - name: generateBasicAuth
          value: "true"
        - name: functionNamespace
          value: openfaas-fn
        - name: operator.create
          value: "true"
    repoURL: https://github.com/openfaas/faas-netes.git
    path: chart/openfaas
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openfaas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
