---
apiVersion: v1
kind: Namespace
metadata:
  name: terrakube
  labels:
    name: terrakube
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terrakube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
    repoURL: https://github.com/AzBuilder/terrakube-helm-chart.git
    path: charts/terrakube
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: terrakube
  syncPolicy:
    automated:
      selfHeal: true
