apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |-
        user:
          namespace: code-server
          storageClassName: microk8s-hostpath
        ingress:
          enabled: false
        image:
          repository: docker.io/nicpayne713/code-server
    repoURL: https://github.com/pypeaday/helm-charts.git
    path: charts/code-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      selfHeal: true
