---
apiVersion: v1
kind: Namespace
metadata:
  name: prefect
  labels:
    name: prefect
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
    repoURL: https://github.com/PrefectHQ/prefect-helm.git
    path: charts/prefect-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: prefect
  syncPolicy:
    automated:
      selfHeal: true
