apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pypeaday/homelab-argocd.git
    path: charts/core-services/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: core-services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
