apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.8
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
#   // We want the MetalLB controller running on the control plane
#   controller_toleration    = [local.control-plane-toleration]
#   controller_node_selector = local.control-plane-node-selector
# }

#   // Change this to fit your needs!
#   data = {
#     config = yamlencode({
#       address-pools = [
#         {
#           name      = "default"
#           protocol  = "layer2"
#           addresses = ["192.168.57.100-192.168.57.254"]
#         }
#       ]
#     })
#   }
